# Generate and run a size-filtered PyInstaller spec for the desktop sidecar.
# Called by apps/desktop/scripts/build-sidecar.ps1
#
# Size strategy (Phase 170+):
# - never use --collect-all (pulls full optional stacks)
# - exclude third-party packages that desktop audit never imports
# - strip leftover pyarrow include/.lib/.pyx development data and test modules
# - keep parquet/core pyarrow + openpyxl for desktop artifact I/O

from __future__ import annotations

import argparse
import subprocess
import sys
import textwrap
from pathlib import Path


def _spec_source(
    *,
    entry: str,
    name: str,
    pathex: list[str],
    mode: str,
) -> str:
    pathex_repr = repr(pathex)

    # Packages with zero call sites in src/dwg_audit for the desktop path, or only
    # pulled as optional/transitive tooling (ezdxf drawing addons, typer pretty CLI,
    # pandas Styler, openpyxl optional backends, declared-but-unused networkx).
    excludes = [
        # Desktop does not ship Streamlit UI.
        "streamlit",
        "matplotlib",
        "tkinter",
        "PySide6",
        "PyQt5",
        "PyQt6",
        "IPython",
        "notebook",
        "pytest",
        # Declared in pyproject but never imported by engine source.
        "networkx",
        # Optional ezdxf drawing stack (image/PDF export). Keep fontTools:
        # ezdxf.fonts.font_manager imports it at module load time.
        "PIL",
        "Pillow",
        "ezdxf.addons.drawing",
        "ezdxf.addons.xqt",
        # Typer help/error formatting requires rich + pygments. Keep both.
        # openpyxl optional backends / extras not required for issues.xlsx write.
        "lxml",
        "xlsxwriter",
        "defusedxml",
        # pandas Styler / HTML template stack (to_html works without jinja2).
        "jinja2",
        "markupsafe",
        # Unused HTTP client stack that can ride along via optional imports.
        "requests",
        "urllib3",
        "charset_normalizer",
        "certifi",
        "idna",
        "httpx",
        "aiohttp",
        # Heavy optional scientific stacks if present in env.
        "scipy",
        "sklearn",
        "numba",
        "llvmlite",
        "sympy",
        "torch",
        "cv2",
        # PyArrow optional extension modules (natives also filtered below).
        "pyarrow.flight",
        "pyarrow.substrait",
        "pyarrow.dataset",
        "pyarrow.cuda",
        "pyarrow.gandiva",
        "pyarrow.orc",
        "pyarrow.acero",
        "pyarrow.csv",
        "pyarrow.feather",
        "pyarrow.json",
        "pyarrow.benchmark",
        "pyarrow.conftest",
        "pyarrow.jvm",
        "pyarrow.interchange",
        "pandas.tests",
        # Keep pandas.testing / pandas._testing: pandas/__init__.py imports testing eagerly.
        "numpy.tests",
        "numpy.testing",
        "networkx.tests",
        # setuptools is large and not needed at runtime for frozen apps.
        "setuptools",
        "pkg_resources",
        "distutils",
    ]

    # Only force packages that desktop audit actually imports.
    # Do NOT force networkx (unused). shapely is used by candidates STRtree.
    hidden = [
        "pandas",
        "pandas._config",
        "pandas._config.config",
        "pandas._config.dates",
        "pandas._config.display",
        "pandas._config.localization",
        "pyarrow",
        "pyarrow.parquet",
        "openpyxl",
        "yaml",
        "shapely",
        "shapely.geometry",
        "shapely.strtree",
        "ezdxf",
        "ezdxf.addons.odafc",
        "fontTools",
        "fontTools.ttLib",
        "rich",
        "pygments",
        "pyparsing",
        "typer",
        # desktop.__init__ uses lazy exports so light SQLite commands do not
        # import the analysis stack at runtime. Frozen fallback commands still
        # need those dynamic modules included in the archive.
        "dwg_audit.desktop.lifecycle",
        "dwg_audit.desktop.preview",
        "dwg_audit.desktop.sidecar",
        "dwg_audit.desktop.state_store",
        "dwg_audit.readers.oda_process",
        "dwg_audit.readers.oda_worker",
    ]

    return textwrap.dedent(
        f"""
        # -*- mode: python ; coding: utf-8 -*-
        # Auto-generated by build_sidecar_pyinstaller.py — do not hand-edit.

        block_cipher = None
        entry = {entry!r}
        name = {name!r}
        pathex = {pathex_repr}
        excludes = {excludes!r}
        hiddenimports = {hidden!r}

        BINARY_DROP_TOKENS = (
            "arrow_flight",
            "arrow_python_flight",
            "arrow_substrait",
            "arrow_dataset",
            "arrow_cuda",
            "arrow_gandiva",
            "arrow_orc",
            "arrow_acero",
            "plasma",
            "_flight",
            "_substrait",
            "_dataset",
            "_orc",
            "_cuda",
            "_gandiva",
            "_acero",
            "_s3fs",
            "_gcsfs",
            "_hdfs",
            "_azurefs",
            "_pyarrow_cpp_tests",
            # Keep libopenblas: numpy depends on it for array math used by pandas/shapely paths.
        )

        def _blob(item):
            return " ".join(str(part).replace("\\\\", "/").lower() for part in item[:2])

        def should_drop_binary(item):
            blob = _blob(item)
            # Always drop optional pyarrow extension stacks.
            if any(tok in blob for tok in BINARY_DROP_TOKENS):
                return True
            if any(tok in blob for tok in ("flight", "substrait", "gandiva", "plasma")):
                return True
            return False

        def should_drop_data(item):
            blob = _blob(item)
            for tok in (
                "matplotlib",
                "streamlit",
                "networkx",
                "pillow",
                "/pil/",
                "\\\\pil\\\\",
                "jinja2",
                "lxml",
                "xlsxwriter",
                "requests",
                "urllib3",
                "setuptools",
                "pyarrow/tests",
                "pandas/tests",
                "numpy/tests",
                # pyarrow ships large C++ headers, import libs, and cython sources
                # that are not needed to run parquet I/O in a frozen app.
                "include/pyarrow",
                "include\\\\pyarrow",
                "pyarrow/include",
                "pyarrow\\\\include",
                "pyarrow/src",
                "pyarrow\\\\src",
                "share/doc",
                "tzdata/zoneinfo/africa",
                "tzdata/zoneinfo/america",
                "tzdata/zoneinfo/antarctica",
                "tzdata/zoneinfo/arctic",
                "tzdata/zoneinfo/asia",
                "tzdata/zoneinfo/atlantic",
                "tzdata/zoneinfo/australia",
                "tzdata/zoneinfo/europe",
                "tzdata/zoneinfo/indian",
                "tzdata/zoneinfo/pacific",
            ):
                if tok in blob:
                    return True
            # Drop C/C++ development artifacts that are not runtime payload.
            if blob.endswith((".lib", ".pyx", ".pxd", ".pxi", ".h", ".hpp", ".cc", ".cpp", ".c")):
                return True
            return False

        a = Analysis(
            [entry],
            pathex=pathex,
            binaries=[],
            datas=[],
            hiddenimports=hiddenimports,
            hookspath=[],
            hooksconfig={{}},
            runtime_hooks=[],
            excludes=excludes,
            win_no_prefer_redirects=False,
            win_private_assemblies=False,
            cipher=block_cipher,
            noarchive=False,
        )

        before_b = len(a.binaries)
        before_d = len(a.datas)
        before_p = len(a.pure)
        a.binaries = [b for b in a.binaries if not should_drop_binary(b)]
        a.datas = [d for d in a.datas if not should_drop_data(d)]

        # Drop pure modules that snuck in via optional import graphs.
        PURE_DROP_PREFIXES = (
            "networkx",
            "PIL",
            "Pillow",
            "jinja2",
            "markupsafe",
            "lxml",
            "xlsxwriter",
            "requests",
            "urllib3",
            "charset_normalizer",
            "certifi",
            "idna",
            "setuptools",
            "pkg_resources",
            "streamlit",
            "matplotlib",
            "IPython",
            "notebook",
            "pytest",
            "scipy",
            "sklearn",
            "numba",
            "pyarrow.flight",
            "pyarrow.substrait",
            "pyarrow.dataset",
            "pyarrow.cuda",
            "pyarrow.gandiva",
            "pyarrow.orc",
            "pyarrow.acero",
            "pyarrow.benchmark",
            "pyarrow.conftest",
            "pyarrow.jvm",
            "pyarrow.interchange",
            "numpy.testing",
            "numpy.tests",
            "ezdxf.addons.drawing",
            "ezdxf.addons.xqt",
        )

        def should_drop_pure(item):
            name = str(item[0]) if item else ""
            return any(name == p or name.startswith(p + ".") for p in PURE_DROP_PREFIXES)

        a.pure = [p for p in a.pure if not should_drop_pure(p)]
        print("[slim] binaries %s -> %s; datas %s -> %s; pure %s -> %s" % (
            before_b, len(a.binaries), before_d, len(a.datas), before_p, len(a.pure)
        ))

        pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

        if {mode!r} == "onefile":
            exe = EXE(
                pyz,
                a.scripts,
                a.binaries,
                a.zipfiles,
                a.datas,
                [],
                name=name,
                debug=False,
                bootloader_ignore_signals=False,
                strip=False,
                upx=False,
                upx_exclude=[],
                runtime_tmpdir=None,
                # Console-subsystem PE keeps stdout/stderr pipes valid. The Rust
                # parent uses CREATE_NO_WINDOW, so users still see no console.
                console=True,
                disable_windowed_traceback=False,
                argv_emulation=False,
                target_arch=None,
                codesign_identity=None,
                entitlements_file=None,
            )
        else:
            exe = EXE(
                pyz,
                a.scripts,
                [],
                exclude_binaries=True,
                name=name,
                debug=False,
                bootloader_ignore_signals=False,
                strip=False,
                upx=False,
                # Console-subsystem PE keeps stdout/stderr pipes valid. The Rust
                # parent uses CREATE_NO_WINDOW, so users still see no console.
                console=True,
                disable_windowed_traceback=False,
                argv_emulation=False,
                target_arch=None,
                codesign_identity=None,
                entitlements_file=None,
            )
            coll = COLLECT(
                exe,
                a.binaries,
                a.zipfiles,
                a.datas,
                strip=False,
                upx=False,
                upx_exclude=[],
                name=name,
            )
        """
    ).lstrip()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--entry", required=True)
    parser.add_argument("--distpath", required=True)
    parser.add_argument("--workpath", required=True)
    parser.add_argument("--specpath", required=True)
    parser.add_argument("--paths", action="append", default=[])
    parser.add_argument("--name", default="dwg-audit-sidecar")
    parser.add_argument("--mode", choices=("onefile", "onedir"), default="onefile")
    parser.add_argument("--python", default=sys.executable)
    args = parser.parse_args(argv)

    entry = str(Path(args.entry).resolve())
    distpath = str(Path(args.distpath).resolve())
    workpath = str(Path(args.workpath).resolve())
    specpath = Path(args.specpath).resolve()
    specpath.mkdir(parents=True, exist_ok=True)
    Path(distpath).mkdir(parents=True, exist_ok=True)
    Path(workpath).mkdir(parents=True, exist_ok=True)

    pathex = [str(Path(p).resolve()) for p in args.paths]
    spec_file = specpath / f"{args.name}.spec"
    spec_file.write_text(
        _spec_source(entry=entry, name=args.name, pathex=pathex, mode=args.mode),
        encoding="utf-8",
    )
    print(f"[slim] wrote spec: {spec_file}")

    cmd = [
        args.python,
        "-m",
        "PyInstaller",
        "--noconfirm",
        "--clean",
        "--distpath",
        distpath,
        "--workpath",
        workpath,
        str(spec_file),
    ]
    print("[slim] running:", " ".join(cmd))
    proc = subprocess.run(cmd, check=False)
    return int(proc.returncode)


if __name__ == "__main__":
    raise SystemExit(main())
