# Generate and run a size-filtered PyInstaller spec for the desktop sidecar.
# Called by apps/desktop/scripts/build-sidecar.ps1

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import textwrap
from pathlib import Path


def _spec_source(
    *,
    entry: str,
    name: str,
    pathex: list[str],
    mode: str,
) -> str:
    pathex_repr = repr(pathex)
    excludes = [
        "streamlit",
        "matplotlib",
        "tkinter",
        "PySide6",
        "PyQt5",
        "PyQt6",
        "IPython",
        "notebook",
        "pytest",
        # Do NOT exclude unittest: pyparsing.testing imports it at module import time.
        "pyarrow.flight",
        "pyarrow.substrait",
        "pyarrow.dataset",
        "pyarrow.cuda",
        "pyarrow.gandiva",
        "pyarrow.orc",
        "pyarrow.acero",
        "pyarrow.csv",
        "pyarrow.feather",
        "pyarrow.json",
        "pandas.tests",
        "numpy.tests",
        "networkx.tests",
    ]
    hidden = [
        "pandas",
        "pyarrow",
        "openpyxl",
        "yaml",
        "shapely",
        "networkx",
        "ezdxf",
        "ezdxf.addons.odafc",
        "pyparsing",
    ]
    return textwrap.dedent(
        f"""
        # -*- mode: python ; coding: utf-8 -*-
        # Auto-generated by build_sidecar_pyinstaller.py — do not hand-edit.

        block_cipher = None
        entry = {entry!r}
        name = {name!r}
        pathex = {pathex_repr}
        excludes = {excludes!r}
        hiddenimports = {hidden!r}

        BINARY_DROP_TOKENS = (
            "arrow_flight",
            "arrow_python_flight",
            "arrow_substrait",
            "arrow_dataset",
            "arrow_cuda",
            "arrow_gandiva",
            "arrow_orc",
            "arrow_acero",
            "plasma",
            "_flight",
            "_substrait",
            "_dataset",
            "_orc",
            "_cuda",
            "_gandiva",
            "_acero",
            "_s3fs",
            "_gcsfs",
            "_hdfs",
            "_azurefs",
            "_pyarrow_cpp_tests",
            # Keep libopenblas: numpy depends on it for array math used by pandas/shapely paths.
        )

        def _blob(item):
            return " ".join(str(part).replace("\\\\", "/").lower() for part in item[:2])

        def should_drop_binary(item):
            blob = _blob(item)
            # Always drop optional pyarrow extension stacks.
            if any(tok in blob for tok in BINARY_DROP_TOKENS):
                return True
            if any(tok in blob for tok in ("flight", "substrait", "gandiva", "plasma")):
                return True
            return False

        def should_drop_data(item):
            blob = _blob(item)
            for tok in (
                "matplotlib",
                "streamlit",
                "pyarrow/tests",
                "pandas/tests",
                "numpy/tests",
                "include/pyarrow",
                "share/doc",
                "tzdata/zoneinfo/africa",
                "tzdata/zoneinfo/america",
                "tzdata/zoneinfo/antarctica",
                "tzdata/zoneinfo/arctic",
                "tzdata/zoneinfo/asia",
                "tzdata/zoneinfo/atlantic",
                "tzdata/zoneinfo/australia",
                "tzdata/zoneinfo/europe",
                "tzdata/zoneinfo/indian",
                "tzdata/zoneinfo/pacific",
            ):
                if tok in blob:
                    return True
            return False

        a = Analysis(
            [entry],
            pathex=pathex,
            binaries=[],
            datas=[],
            hiddenimports=hiddenimports,
            hookspath=[],
            hooksconfig={{}},
            runtime_hooks=[],
            excludes=excludes,
            win_no_prefer_redirects=False,
            win_private_assemblies=False,
            cipher=block_cipher,
            noarchive=False,
        )

        before_b = len(a.binaries)
        before_d = len(a.datas)
        a.binaries = [b for b in a.binaries if not should_drop_binary(b)]
        a.datas = [d for d in a.datas if not should_drop_data(d)]
        print("[slim] binaries %s -> %s; datas %s -> %s" % (
            before_b, len(a.binaries), before_d, len(a.datas)
        ))

        pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

        if {mode!r} == "onefile":
            exe = EXE(
                pyz,
                a.scripts,
                a.binaries,
                a.zipfiles,
                a.datas,
                [],
                name=name,
                debug=False,
                bootloader_ignore_signals=False,
                strip=False,
                upx=False,
                upx_exclude=[],
                runtime_tmpdir=None,
                console=True,
                disable_windowed_traceback=False,
                argv_emulation=False,
                target_arch=None,
                codesign_identity=None,
                entitlements_file=None,
            )
        else:
            exe = EXE(
                pyz,
                a.scripts,
                [],
                exclude_binaries=True,
                name=name,
                debug=False,
                bootloader_ignore_signals=False,
                strip=False,
                upx=False,
                console=True,
                disable_windowed_traceback=False,
                argv_emulation=False,
                target_arch=None,
                codesign_identity=None,
                entitlements_file=None,
            )
            coll = COLLECT(
                exe,
                a.binaries,
                a.zipfiles,
                a.datas,
                strip=False,
                upx=False,
                upx_exclude=[],
                name=name,
            )
        """
    ).lstrip()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--entry", required=True)
    parser.add_argument("--distpath", required=True)
    parser.add_argument("--workpath", required=True)
    parser.add_argument("--specpath", required=True)
    parser.add_argument("--paths", action="append", default=[])
    parser.add_argument("--name", default="dwg-audit-sidecar")
    parser.add_argument("--mode", choices=("onefile", "onedir"), default="onefile")
    parser.add_argument("--python", default=sys.executable)
    args = parser.parse_args(argv)

    entry = str(Path(args.entry).resolve())
    distpath = str(Path(args.distpath).resolve())
    workpath = str(Path(args.workpath).resolve())
    specpath = Path(args.specpath).resolve()
    specpath.mkdir(parents=True, exist_ok=True)
    Path(distpath).mkdir(parents=True, exist_ok=True)
    Path(workpath).mkdir(parents=True, exist_ok=True)

    pathex = [str(Path(p).resolve()) for p in args.paths]
    spec_file = specpath / f"{args.name}.spec"
    spec_file.write_text(
        _spec_source(entry=entry, name=args.name, pathex=pathex, mode=args.mode),
        encoding="utf-8",
    )
    print(f"[slim] wrote spec: {spec_file}")

    cmd = [
        args.python,
        "-m",
        "PyInstaller",
        "--noconfirm",
        "--clean",
        "--distpath",
        distpath,
        "--workpath",
        workpath,
        str(spec_file),
    ]
    print("[slim] running:", " ".join(cmd))
    proc = subprocess.run(cmd, check=False)
    return int(proc.returncode)


if __name__ == "__main__":
    raise SystemExit(main())
